window.WEBSITES = [
  { label: 'Media Management Frontend', category: 'media', port: 3000, path: '/', note: 'React App' },
  { label: 'PotatoMusic', category: 'media', port: 5173, path: '/', note: 'Music frontend' },
  { label: 'CouchDB', category: 'system', port: 5984, path: '/', note: 'DB admin/API' },
  { label: 'Radarr', category: 'media', port: 7878, path: '/', note: 'Movie management' },
  { label: 'Media API', category: 'system', port: 8000, path: '/', note: 'Web/API endpoint' },
  { label: 'PotatoMusic Backend', category: 'system', port: 8001, path: '/', note: 'API endpoint' },
  { label: 'Koel', category: 'media', port: 8003, path: '/', note: 'Music server' },
  { label: 'qBittorrent', category: 'tools', port: 8080, path: '/', note: 'Torrent WebUI' },
  { label: 'Jellyfin', category: 'media', port: 8096, path: '/web/', note: 'Media server' },
  { label: 'Stock Daily Report', category: 'tools', port: 8781, path: '/reports/daily', note: 'Daily stock report' },
  { label: 'Service UI', category: 'system', port: 8191, path: '/', note: 'Web endpoint' },
  { label: 'Service UI', category: 'system', port: 8781, path: '/', note: 'Web/API endpoint' },
  { label: 'Sonarr', category: 'media', port: 8989, path: '/', note: 'TV management' },
  { label: 'Prowlarr', category: 'tools', port: 9696, path: '/', note: 'Indexer management' },
  { label: 'HK Parking Map', category: 'tools', port: 18080, path: '/', note: 'Parking visualization' },
  { label: 'OpenClaw Control', category: 'tools', port: 18789, path: '/', note: 'Agent control panel' },
  { label: 'HA Sensor Dashboard', category: 'tools', port: 18888, path: '/', note: 'HA temp/humidity dashboard' },
  {
    label: 'Desktop VNC',
    category: 'system',
    port: 6082,
    path: '/vnc_lite.html?scale=true&path=websockify',
    note: 'noVNC web client',
  },
  {
    label: 'Home Assistant',
    category: 'tools',
    port: 8123,
    url: 'http://192.168.50.137:8123/lovelace/0',
    note: 'HA Lovelace dashboard',
  },
];
